### ISSUE TITLE
Bug: using trainer card

### ISSUE THREAD

**Issue by z-mehta** [h0111in/PokemonGoBack#45]
While using trainer card the message is displayed that active area is empty......but active card was there and unable to execute trainer card.
@h0111in  look into the implementation of the trainer cards.
it is not working

**Comment by h0111in** [comment]
it is fixed just now.

**Comment by z-mehta** [comment]
while using Wally trainer card - search ability , it does not work properly........no effect was there and the card disappeared giving the following error:


Jun 25, 2017 12:47:51 AM View.GameBoardController$2 popCard
INFO: evt :Area deck - ID: A26 - smallCardId:  - columnIndex:-1
Jun 25, 2017 12:47:51 AM Model.Player addCard
INFO: A26 Area : hand columnIndex: -1 uiHolderId: 
Jun 25, 2017 12:47:51 AM View.GameBoardController$2 pushCard
INFO: evt :Area hand - ID: A26 - smallCardId:  - columnIndex:-1
Jun 25, 2017 12:47:51 AM Controller.LogicController$3 cardClicked
INFO: A41
Jun 25, 2017 12:47:51 AM View.GameBoardController$2$1 cardClicked
INFO: senderA41 evt :A41
Jun 25, 2017 12:48:05 AM Model.Attack getCostString
INFO: cost =  
Jun 25, 2017 12:48:07 AM Model.Player popCard
INFO: A27 Area : hand columnIndex: -1 uiHolderId: 
Jun 25, 2017 12:48:07 AM View.GameBoardController$2 popCard
INFO: evt :Area hand - ID: A27 - smallCardId:  - columnIndex:-1
java.lang.NullPointerException
	at Model.Abilities.BaseAction.getTargetPlayer(BaseAction.java:82)
	at Model.Abilities.Search.fight(Search.java:48)
	at Model.Abilities.ActionComposite.fight(ActionComposite.java:64)
	at Controller.LogicController.executeAbility(LogicController.java:447)
	at Controller.LogicController$3.attackRequest(LogicController.java:784)
	at View.SmallCardController.fireAttack(SmallCardController.java:468)
	at View.SmallCardController$2.handle(SmallCardController.java:124)
	at View.SmallCardController$2.handle(SmallCardController.java:105)
	at com.sun.javafx.event.CompositeEventHandler.dis

@h0111in look into it

**Comment by h0111in** [comment]
The card goes to discard, but about the search ability, please give me a clear step for running search ability for example which steps should be executed for Wally.

**Comment by z-mehta** [comment]
you can find the steps in #51 @h0111in let me know if any doubt

**Comment by z-mehta** [comment]
@h0111in are you sure that this ability(wally trainer card) is implemented as the way it has to be?

**Comment by h0111in** [comment]
please explain what you expect
