### ISSUE TITLE
Bug: while attaching energy to bench

### ISSUE THREAD

**Issue by z-mehta** [h0111in/PokemonGoBack#46]
@h0111in  while attaching energy t0 bench it is showing this error.
Jun 23, 2017 5:31:20 PM Controller.LogicController playAI
INFO: attachEnergyOnBench:Water
Jun 23, 2017 5:31:20 PM Model.Player popCard
INFO: B25
java.lang.Exception: Bench is full
	at Model.Player.addCard(Player.java:104)
	at Model.Player.addCard(Player.java:127)
	at Controller.LogicController.playAI(LogicController.java:238)
	at Controller.LogicController.startTurn(LogicController.java:137)
	at Controller.LogicController.access$600(LogicController.java:27)
	at Controller.LogicController$3.attackRequest(LogicController.java:670)
	at View.SmallCardController.fireAttack(SmallCardController.java:444)
	at View.SmallCardController$2.handle(SmallCardController.java:127)
	at View.SmallCardController$2.handle(SmallCardController.java:108)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.ja

**Comment by h0111in** [comment]
I could not find the bug, but I attached some extra logger around. please download the latest code and try to after observe the bug, send the log for me.

**Comment by z-mehta** [comment]
okok
i ll do it

**Comment by h0111in** [comment]
check the latest code.some improvements took placed about it.

**Comment by z-mehta** [comment]
not sure where this error is related to the code

just read the log for reference: its in the Player. java fileJun 24, 2017 1:34:47 AM Model.Player addCard
INFO: column Index is not found=>B48
java.lang.Exception: Bench is full
	at Model.Player.addCard(Player.java:112)
	at Model.Player.addCard(Player.java:76)
	at Controller.LogicController.playAI(LogicController.java:219)
	at Controller.LogicController.startTurn(LogicController.java:189)
	at Controller.LogicController.access$600(LogicController.java:27)
	at Controller.LogicController$3.attackRequest(LogicController.java:778)
	at View.SmallCardController.fireAttack(SmallCardController.java:468)
	at View.SmallCardController$2.handle(SmallCardController.java:124)
	at View.SmallCardController$2.handle(SmallCardController.java:105)

**Comment by z-mehta** [comment]
**Additional info::**

INFO: cardHolder.getId()=> 
Jun 24, 2017 1:34:47 AM Model.Player addCard
INFO:     ->B25
Jun 24, 2017 1:34:47 AM Model.Player addCard
INFO: column Index is not found=>B48
java.lang.Exception: Bench is full

**Comment by z-mehta** [comment]
fixed
