### ISSUE TITLE
Bug- Sleep Poison is not working

### ISSUE THREAD

**Issue by z-mehta** [h0111in/PokemonGoBack#48]
@h0111in  ability sleep poison is not working properly.

Error:

:     ->B11
Jun 23, 2017 7:00:53 PM Model.Player addCard
INFO: cardHolder.getId()=> 
Jun 23, 2017 7:00:53 PM Model.Player addCard
INFO:     ->B24
Jun 23, 2017 7:00:53 PM Model.Player addCard
INFO: column Index is not found=>B55
java.lang.Exception: Bench is full
	at Model.Player.addCard(Player.java:112)
	at Model.Player.addCard(Player.java:76)
	at Controller.LogicController.playAI(LogicController.java:167)
	at Controller.LogicController.startTurn(LogicController.java:137)
	at Controller.LogicController.access$600(LogicController.java:27)
	at Controller.LogicController$3.attackRequest(LogicController.java:670)
	at View.SmallCardController.fireAttack(SmallCardController.java:444)
	at View.SmallCardController$2.handle(SmallCardController.java:127)
	at View.SmallCardController$2.handle(SmallCardController.java:108)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)

**Comment by h0111in** [comment]
please check it again with latest update.

**Comment by z-mehta** [comment]
yes it is working now.......but instead of causing 10 damage to opponent itself, when opponent go for a attack after poisoning. the damage is caused by only 1 hitpoint

**Comment by z-mehta** [comment]
no........its working properly.
@h0111in it will cause 1 damage counter every turn after getting poisoned.
issue is fixed.
thankyou
