### ISSUE TITLE
bug:

### ISSUE THREAD

**Issue by z-mehta** [h0111in/PokemonGoBack#50]
@h0111in This exception is occurring frequently and this exception is caught since last two updates. it is related to so many moves
#46 

look into it:

un 24, 2017 2:23:36 AM Model.Player addCard
INFO: cardHolder.getId()=> 
Jun 24, 2017 2:23:36 AM Model.Player addCard
INFO: column Index is not found=>B25
java.lang.Exception: Bench is full
	at Model.Player.addCard(Player.java:120)
	at Model.Player.addCard(Player.java:143)
	at Controller.LogicController.playAI(LogicController.java:292)
	at Controller.LogicController.startTurn(LogicController.java:189)
	at Controller.LogicController.access$600(LogicController.java:27)
	at Controller.LogicController$3.attackRequest(LogicController.java:781)
	at View.SmallCardController.fireAttack(SmallCardController.java:468)
	at View.SmallCardController$2.handle(SmallCardController.java:124)
	at View.SmallCardController$2.handle(SmallCardController.java:105)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at

**Comment by h0111in** [comment]
yes, check the last update.it works!

**Comment by z-mehta** [comment]
not seen again. thx @h0111in
