### ISSUE TITLE
bug : retreat(when bench n active pokemon have attached energy with them)

### ISSUE THREAD

**Issue by z-mehta** [h0111in/PokemonGoBack#53]
when i go for retreat.................if the both bench and active pokemon have energy attached to it.
the both cards disappeared after retreat.
#52 
below is the error:

INFO: evt :Area bench - ID: A42 - smallCardId:  - columnIndex:1
Jun 24, 2017 2:55:22 AM Model.Player popCard
INFO: A36 Area : bench columnIndex: -1 uiHolderId: A42
Jun 24, 2017 2:55:22 AM View.GameBoardController$2 popCard
INFO: evt :Area bench - ID: A36 - smallCardId: A42 - columnIndex:1
java.lang.NullPointerException
	at View.GameBoardController$2.popCard(GameBoardController.java:227)
	at Model.Player.fireRemoveCard(Player.java:349)
	at Model.Player.popCard(Player.java:309)
	at Model.Player.popCard(Player.java:285)
	at Model.Player.swapCardHolder(Player.java:438)
	at Controller.LogicController.executeRetreat(LogicController.java:402)
	at Controller.LogicController.access$900(LogicController.java:27)
	at Controller.LogicController$3.attackRequest(LogicController.java:737)
	at View.SmallCardController.fireAttack(SmallCardController.java:468)
	at View.SmallCardController$2.handle(SmallCardController.java:124)
	at View.SmallCardController$2.handle(SmallCardController.java:105)
@h0111in  look into it

**Comment by h0111in** [comment]
it is fixed. check it please.

**Comment by z-mehta** [comment]
it is fixed.....thx @h0111in
